from enum import Enum

class InterviewStatusEnum(Enum):
    START = "START"
    PARSE_EMAIL = "PARSE_EMAIL"
    VALIDATE_INVITATION = "VALIDATE_INVITATION"
    CREATE_CALENDAR_EVENT = "CREATE_CALENDAR_EVENT"
    WAITING = "WAITING"
    AWAITING_RESPONSES = "AWAITING_RESPONSES"
    CREATE_JOIN_MEETING = "CREATE_JOIN_MEETING"
    RUN_INTERVIEW_SIMULATION = "RUN_INTERVIEW_SIMULATION"
    EVALUATE_CANDIDATE = "EVALUATE_CANDIDATE"
    GENERATE_REPORT = "GENERATE_REPORT"
    SEND_EMAIL_REPORT = "SEND_EMAIL_REPORT"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"